baseURL = "https://titikmula.xyz/"
languageCode = "en-us"
title = "titikmula"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "titikmula - All rights reserved"
enableEmoji = true
publishDir = "public"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  logo = "/images/logo.png"
  description ="Taman Baca - Ruang Bersama - Ruang Kreatif"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Titik Mula"
  thumbnail = "/images/logo.png"
  description = "Creator of this blog."

[params.index]
  picture = "/images/open-magazine.png"
  title = "Titik Mula"
  subtitle = "Taman Baca - Ruang Bersama - Ruang Kreatif"
  mdtext = '''Waras dengan Membaca
  '''
  alertbar = false

[params.social]
  medium = "titikmula"
  twitter = "titikmula"
  instagram = "titikmula"

## Main Menu
[[menu.main]]
    name = "Cerita"
    weight = 100
    identifier = "cerita"
    url = "/cerita"
[[menu.main]]
    name = "Tentang"
    identifier = "tentang"
    weight = 200
    url = "/tentang"
# [[menu.main]]
#     name = "Kontak"
#     identifier = "kontak"
#     weight = 200
#     url = "/kontak"
